services:
  linux:
    build: ./linux
    image: basic-linux:1.0

  web:
    build: ./web
    image: basic-web:1.0
    depends_on:
      - linux
    ports:
      - "8080:80"
    volumes:
      - ./logs:/logs
